name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: calculahet hash on 7 char
        run: echo "sha7=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        id: sha_shortening
      - name: execute curl
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{github.repository}}/issues \
          -d '{"title":"Found a bug: ${{steps.sha_shortening.outputs.sha7}}","body":"I'\''m having a problem with this.","labels":["bug"]}'